# Level and Power

In [41]:
from joblib import Parallel, delayed
from tqdm import tqdm

import numpy as np
import polars as pl
from scipy.linalg import sqrtm
from scipy.stats import chi2

import pickle
from pathlib import Path
from typing import Callable

from gpy_test import GPY

from data_generation.arma import (
    generate_arma_sample,
    generate_arma_covariance_matrix,
)

from data_generation.other import (
    factor_model_sample,
    common_random_dependence_sample,
)

In [ ]:
# We reproduce here the settings used for LRV
fs = [lambda x: (x - 1) ** 2]

alpha = 0.66
N_range = np.linspace(1000, 8000, 8)
c = 1 / 2  # not really needed, but that's to reproduce the same M as for LRV test

# default values for the iid time series. We choose a small AR as that
# creates a very spiky spectral density if too large
time_ar, time_ma = 0.1, 0.5

# always repeat an experiment K times
n_repeats = 10**4

# threshold to detect
level = 0.1
chi2_values = chi2.ppf(np.array([level / 2, 1 - level / 2]), df=len(fs))

# generate real gaussian data
is_complex_gaussian = True

# various computation (complex contour integral) should result in a
# real value. We check that the imaginary part is smaller than this
tolerance = 1e-5

# path to the stored experiment results for easy reloading
data_storage_path = "./data/{experiment_type}/{experiment_id}.pickle"

In [43]:
# Define the functions to store and load experiment results
def run_batch(
    run: Callable, n_repeats: int, experiment_type: str, run_kwargs: dict
) -> None:
    experiment_id = "_".join(
        f"{key}={value}"
        for key, value in run_kwargs.items()
        if isinstance(value, int) or isinstance(value, float)
    )
    resolved_data_path = Path(
        data_storage_path.format(
            experiment_type=experiment_type, experiment_id=experiment_id
        )
    )
    if resolved_data_path.exists():
        return

    print(f"Running experiment {experiment_type} with id {experiment_id}")

    resolved_data_path.parent.mkdir(parents=True, exist_ok=True)

    results = [run(**run_kwargs) for _ in range(n_repeats)]
    with open(resolved_data_path, "wb") as handle:
        pickle.dump(results, handle)


def load_batch(experiment_type: str) -> pl.DataFrame:
    # load the samples
    all_results = []

    resolved_data_path = Path(
        data_storage_path.format(experiment_type=experiment_type, experiment_id="none")
    ).parent
    for file in resolved_data_path.iterdir():
        if file.stem == ".DS_Store":
            continue

        with open(file, "rb") as handle:
            results = pickle.load(handle)
        all_results += results

    return pl.DataFrame(all_results)

# Level check
# ARMA time series

## Constant ARMA coefs

In [44]:
def run(
    N,
    M,
    time_ar,
    time_ma,
    is_complex_gaussian,
):
    y = generate_arma_sample(
        N,
        M,
        time_ar,
        time_ma,
        is_complex_gaussian,
    )

    gpy_result = GPY(y, fs, is_complex_gaussian=is_complex_gaussian)

    return {
        "N": N,
        "M": M,
        "time_ar": time_ar,
        "time_ma": time_ma,
        "is_complex_gaussian": is_complex_gaussian,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }

In [45]:
tasks = []
for N in N_range:
    M = int(N**alpha * c)

    task = (
        run,
        n_repeats,
        f"arma_no_dependence",
        {
            "N": int(N),
            "M": int(M),
            "time_ar": time_ar,
            "time_ma": time_ma,
            "is_complex_gaussian": is_complex_gaussian,
        },
    )

    tasks.append(task)

# shuffle the tasks to distribute the load over time
np.random.shuffle(tasks)
results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch(f"arma_no_dependence")
pivot = (
    df.with_columns(
        [
            # (pl.col("p_value") < level).alias("is_test_positive").cast(pl.Float64),
            (
                (pl.col("test_statistic") < chi2_values[0])
                | (pl.col("test_statistic") > chi2_values[1])
            )
            .alias("is_test_positive")
            .cast(pl.Float64),
        ]
    )
    .group_by(["N"])
    .mean()
    .to_pandas()
)
pivot[["N", "is_test_positive"]].sort_values("N")

100%|██████████| 8/8 [00:00<00:00, 9467.95it/s]

      N  is_test_positive
6  1000              0.06
7  2000              0.05
0  3000              0.12
5  4000              0.08
1  5000              0.06
3  6000              0.11
2  7000              0.14
4  8000              0.13

## Random ARMA coefs

In [46]:
def run(
    N,
    M,
    is_complex_gaussian,
):
    ar, ma = np.random.uniform(-0.5, 0.5, M), np.random.uniform(-0.5, 0.5, M)

    y = generate_arma_sample(
        N,
        M,
        ar,
        ma,
        is_complex_gaussian,
    )

    gpy_result = GPY(y, fs, is_complex_gaussian=is_complex_gaussian)

    return {
        "N": N,
        "M": M,
        "is_complex_gaussian": is_complex_gaussian,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }

In [47]:
tasks = []
for N in N_range:
    M = int(N**alpha * c)

    task = (
        run,
        n_repeats,
        f"arma_no_dependence_multidim",
        {
            "N": int(N),
            "M": int(M),
            "is_complex_gaussian": is_complex_gaussian,
        },
    )

    tasks.append(task)

# shuffle the tasks to distribute the load over time
np.random.shuffle(tasks)
results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))


df = load_batch(f"arma_no_dependence_multidim")
pivot = (
    df.with_columns(
        [
            # (pl.col("p_value") < level).alias("is_test_positive").cast(pl.Float64),
            (
                (pl.col("test_statistic") < chi2_values[0])
                | (pl.col("test_statistic") > chi2_values[1])
            )
            .alias("is_test_positive")
            .cast(pl.Float64),
        ]
    )
    .group_by(["N"])
    .mean()
    .to_pandas()
)
pivot[["N", "is_test_positive"]].sort_values("N")

100%|██████████| 8/8 [00:00<00:00, 13911.46it/s]

      N  is_test_positive
4  1000              0.61
1  2000              0.67
7  3000              0.78
5  4000              0.76
6  5000              0.81
0  6000              0.82
2  7000              0.81
3  8000              0.80

# Power check

## ARMA covariance structure

In [48]:
def run(
    N,
    M,
    time_ar,
    time_ma,
    space_ar_1,
    space_ar_2,
    space_ma_1,
    space_ma_2,
    is_complex_gaussian,
):
    y = generate_arma_sample(
        N,
        M,
        time_ar,
        time_ma,
        is_complex_gaussian,
    )
    # Cov_1 = generate_arma_covariance_matrix(M // 2, space_ar_1, space_ma_1)
    # Cov_2 = generate_arma_covariance_matrix(M - M // 2, space_ar_2, space_ma_2)
    # Cov = np.block(
    #     [
    #         [Cov_1, np.zeros((M // 2, M - M // 2))],
    #         [np.zeros((M - M // 2, M // 2)), Cov_2],
    #     ]
    # )
    Cov = generate_arma_covariance_matrix(M, space_ar_1, space_ma_1)
    y = y @ sqrtm(Cov)

    gpy_result = GPY(y, fs, is_complex_gaussian=is_complex_gaussian)

    return {
        "N": N,
        "M": M,
        "time_ar": time_ar,
        "time_ma": time_ma,
        "space_ar_1": space_ar_1,
        "space_ma_1": space_ma_1,
        "space_ar_2": space_ar_2,
        "space_ma_2": space_ma_2,
        "is_complex_gaussian": is_complex_gaussian,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }

In [49]:
# ARMA covariance structure
space_ar = 0.05

tasks = []
for N in N_range:
    B = int(N**alpha)
    if B % 2 == 0:
        B -= 1
    M = int(B * c)

    task = (
        run,
        n_repeats,
        f"ar_dependence",
        {
            "N": int(N),
            "M": int(M),
            "time_ar": time_ar,
            "time_ma": time_ma,
            "space_ar_1": space_ar,
            "space_ma_1": 0,
            "space_ar_2": space_ar,
            "space_ma_2": 0,
            "is_complex_gaussian": is_complex_gaussian,
        },
    )

    tasks.append(task)

# shuffle the tasks to distribute the load over time
np.random.shuffle(tasks)
results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch(f"ar_dependence").drop(["time_ar", "time_ma"])
pivot = (
    df.with_columns(
        [
            # (pl.col("p_value") < level).alias("is_test_positive").cast(pl.Float64),
            (
                (pl.col("test_statistic") < chi2_values[0])
                | (pl.col("test_statistic") > chi2_values[1])
            )
            .alias("is_test_positive")
            .cast(pl.Float64),
        ]
    )
    .group_by(["N"])
    .mean()
    .sort("N")
    .to_pandas()
)
pivot[["N", "is_test_positive"]].sort_values("N")

100%|██████████| 8/8 [00:00<00:00, 14814.32it/s]

      N  is_test_positive
0  1000              0.11
1  2000              0.09
2  3000              0.14
3  4000              0.09
4  5000              0.08
5  6000              0.06
6  7000              0.09
7  8000              0.09

## Common random dependence

In [50]:
def run(
    N,
    M,
    time_ar,
    time_ma,
    mixing_scale,
    is_complex_gaussian,
):
    y = common_random_dependence_sample(
        N, M, time_ar, time_ma, mixing_scale, is_complex_gaussian
    )

    gpy_result = GPY(y, fs, is_complex_gaussian=is_complex_gaussian)

    return {
        "N": N,
        "M": M,
        "time_ar": time_ar,
        "time_ma": time_ma,
        "mixing_scale": mixing_scale,
        "is_complex_gaussian": is_complex_gaussian,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }

In [51]:
# ARMA covariance structure
mixing_scale = 1.0

tasks = []
for N in N_range:
    B = int(N**alpha)
    if B % 2 == 0:
        B -= 1
    M = int(B * c)

    task = (
        run,
        n_repeats,
        f"common_random_dependence",
        {
            "N": int(N),
            "M": int(M),
            "time_ar": time_ar,
            "time_ma": time_ma,
            "mixing_scale": mixing_scale,
            "is_complex_gaussian": is_complex_gaussian,
        },
    )

    tasks.append(task)

# shuffle the tasks to distribute the load over time
np.random.shuffle(tasks)
results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch(f"common_random_dependence").drop(["time_ar", "time_ma"])
pivot = (
    df.with_columns(
        [
            # (pl.col("p_value") < level).alias("is_test_positive").cast(pl.Float64),
            (
                (pl.col("test_statistic") < chi2_values[0])
                | (pl.col("test_statistic") > chi2_values[1])
            )
            .alias("is_test_positive")
            .cast(pl.Float64),
        ]
    )
    .group_by(["N"])
    .mean()
    .sort("N")
    .to_pandas()
)
pivot[["N", "is_test_positive"]].sort_values("N")

100%|██████████| 8/8 [00:00<00:00, 2195.25it/s]

      N  is_test_positive
0  1000              0.18
1  2000              0.19
2  3000              0.23
3  4000              0.14
4  5000              0.20
5  6000              0.14
6  7000              0.18
7  8000              0.19

## Factor model

In [52]:
def run(
    N,
    M,
    r,
    snr,
    time_ar,
    time_ma,
    is_complex_gaussian,
):
    y = factor_model_sample(N, M, r, time_ar, time_ma, snr, is_complex_gaussian)
    gpy_result = GPY(y, fs)
    return {
        "N": N,
        "M": M,
        "r": r,
        "snr": snr,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }

In [54]:
snr_range = [0.05, 0.1]
r = 1

tasks = []
for snr in snr_range:
    for N in N_range:
        B = int(N**alpha)
        if B % 2 == 0:
            B -= 1
        M = int(B * c)

        task = (
            run,
            n_repeats,
            f"factor_model",
            {
                "N": int(N),
                "M": int(M),
                "r": r,
                "snr": snr,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )

        tasks.append(task)

# shuffle the tasks to distribute the load over time
np.random.shuffle(tasks)
results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch(f"factor_model")
pivot = (
    df.with_columns(
        [
            # (pl.col("p_value") < level).alias("is_test_positive").cast(pl.Float64),
            (
                (pl.col("test_statistic") < chi2_values[0])
                | (pl.col("test_statistic") > chi2_values[1])
            )
            .alias("is_test_positive")
            .cast(pl.Float64),
        ]
    )
    .group_by(["N", "snr"])
    .mean()
    .to_pandas()
    .pivot(index="N", columns=["snr"], values="is_test_positive")
)
pivot

100%|██████████| 16/16 [00:00<00:00, 13299.42it/s]

snr   0.05  0.10
N
1000  0.09  0.06
2000  0.11  0.13
3000  0.06  0.11
4000  0.05  0.06
5000  0.11  0.06
6000  0.10  0.09
7000  0.08  0.12
8000  0.06  0.05