# Power

In [1]:
from joblib import Parallel, delayed
from tqdm import tqdm

import numpy as np
import polars as pl
from gpy_test import GPY
from scipy.linalg import sqrtm
import pickle
from pathlib import Path
from typing import Callable

from data import (
    white_arma_sample,
    arma_covariance,
    non_linear_sample,
    factor_model_sample,
    arch_sample,
)

In [2]:
# for the GPY test, we will always use the following test functions
fs = [lambda x: x, lambda x: x**2]

# we will always evaluate the test against these values of N and M
T_range = np.arange(50, 400 + 50, 50)
M_range = np.arange(50, 400 + 50, 50)

# always repeat an experiment 1000 times
n_repeats = 1000

# always throw the first 100 time series samples
burn = 100

# threshold to detect
level = 0.05

# generate real gaussian dataXC
is_complex_gaussian = False

# path to the stored experiment results for easy reloading
data_filepath_format = "data/{experiment_type}/{experiment_id}.pickle"

In [3]:
# Define the functions to store and load experiment results
def run_batch(
    run: Callable, n_repeats: int, experiment_type: str, run_kwargs: dict
) -> None:
    experiment_id = "_".join(f"{key}={value}" for key, value in run_kwargs.items())
    resolved_data_path = Path(
        data_filepath_format.format(
            experiment_type=experiment_type, experiment_id=experiment_id
        )
    )
    if resolved_data_path.exists():
        return

    resolved_data_path.parent.mkdir(parents=True, exist_ok=True)

    results = [run(**run_kwargs) for _ in range(n_repeats)]
    with open(resolved_data_path, "wb") as handle:
        pickle.dump(results, handle)


def load_batch(experiment_type: str) -> pl.DataFrame:
    # load the samples
    all_results = []

    resolved_data_path = Path(
        data_filepath_format.format(
            experiment_type=experiment_type, experiment_id="none"
        )
    ).parent
    for file in resolved_data_path.iterdir():
        if file.stem == ".DS_Store":
            continue

        with open(file, "rb") as handle:
            results = pickle.load(handle)
        all_results += results

    return pl.DataFrame(all_results)

# Level check
# MA time series

In [4]:
def run(T, M, burn, time_ar, time_ma, space_ar_1, space_ma_1, space_ar_2, space_ma_2, is_complex_gaussian):
    y = white_arma_sample(
        T, M, burn, ar=time_ar, ma=time_ma, is_complex_gaussian=is_complex_gaussian
    )
    half_M = int(M/2)
    space_cov_1 = arma_covariance(half_M, space_ar_1, space_ma_1)
    space_cov_sqrt_1 = sqrtm(space_cov_1)
    space_cov_2 = arma_covariance(M-half_M, space_ar_2, space_ma_2)
    space_cov_sqrt_2 = sqrtm(space_cov_2)
    y[:, :half_M] = y[:, :half_M] @ space_cov_sqrt_1
    y[:, half_M:] = y[:, half_M:] @ space_cov_sqrt_2

    gpy_result = GPY(y, fs, is_complex_gaussian=is_complex_gaussian)
    return {
        "T": T,
        "M": M,
        "burn": burn,
        "time_ar": time_ar,
        "time_ma": time_ma,
        "space_ar_1": space_ar_1,
        "space_ma_1": space_ma_1,
        "space_ar_2": space_ar_2,
        "space_ma_2": space_ma_2,
        "is_complex_gaussian": is_complex_gaussian,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }


time_ar, time_ma = 0.2, 0
space_ar_1, space_ma_1 = 0, 0
space_ar_2, space_ma_2 = 0, 0

tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "ma_no_dependence",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "space_ar_1": space_ar_1,
                "space_ma_1": space_ma_1,
                "space_ar_2": space_ar_2,
                "space_ma_2": space_ma_2,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("ma_no_dependence")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(
    (pl.col("test_statistic") > 1.4).alias(positive_column_name).cast(pl.Float64)
).group_by(["T", "M", "time_ar", "time_ma"]).mean().to_pandas().pivot(
    index="T", columns=["M"], values=[positive_column_name]
)

  6%|▋         | 4/64 [00:00<00:05, 11.03it/s]

100%|██████████| 64/64 [4:07:13<00:00, 231.78s/it]

    positive - 5%
M             50     100    150    200    250    300    350    400
T
50          0.452  0.404  0.370  0.354  0.370  0.329  0.321  0.324
100         0.520  0.431  0.441  0.404  0.386  0.361  0.352  0.370
150         0.566  0.497  0.425  0.447  0.412  0.398  0.392  0.387
200         0.593  0.501  0.460  0.459  0.419  0.436  0.404  0.401
250         0.629  0.545  0.523  0.469  0.447  0.450  0.449  0.425
300         0.645  0.563  0.537  0.460  0.481  0.446  0.418  0.435
350         0.671  0.609  0.534  0.519  0.499  0.455  0.458  0.455
400         0.716  0.594  0.550  0.521  0.481  0.486  0.479  0.455

## AR time series

In [5]:
time_ar, time_ma = 0, 0.8
space_ar_1, space_ma_1 = 0, 0
space_ar_2, space_ma_2 = 0, 0

tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "ar_no_dependence",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "space_ar_1": space_ar_1,
                "space_ma_1": space_ma_1,
                "space_ar_2": space_ar_2,
                "space_ma_2": space_ma_2,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("ar_no_dependence")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(
    (pl.col("test_statistic") > 1.4).alias(positive_column_name).cast(pl.Float64)
).group_by(["T", "M", "time_ar", "time_ma"]).mean().to_pandas().pivot(
    index="T", columns=["M"], values=[positive_column_name]
)

100%|██████████| 64/64 [4:02:54<00:00, 227.73s/it]

    positive - 5%
M             50     100    150    200    250    300    350    400
T
50          0.431  0.388  0.380  0.348  0.352  0.307  0.326  0.301
100         0.479  0.413  0.417  0.356  0.348  0.370  0.378  0.367
150         0.537  0.454  0.431  0.414  0.414  0.368  0.360  0.351
200         0.573  0.492  0.481  0.417  0.374  0.418  0.398  0.382
250         0.598  0.517  0.511  0.453  0.434  0.399  0.421  0.378
300         0.631  0.515  0.491  0.502  0.459  0.437  0.403  0.419
350         0.620  0.569  0.484  0.478  0.455  0.454  0.427  0.421
400         0.664  0.549  0.513  0.493  0.464  0.430  0.421  0.456

## ARMA time series

In [6]:
time_ar, time_ma = 0.2, 0.8
space_ar_1, space_ma_1 = 0, 0
space_ar_2, space_ma_2 = 0, 0

tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "arma_no_dependence",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "space_ar_1": space_ar_1,
                "space_ma_1": space_ma_1,
                "space_ar_2": space_ar_2,
                "space_ma_2": space_ma_2,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("arma_no_dependence")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(
    (pl.col("test_statistic") > 1.4).alias(positive_column_name).cast(pl.Float64)
).group_by(["T", "M", "time_ar", "time_ma"]).mean().to_pandas().pivot(
    index="T", columns=["M"], values=[positive_column_name]
)

  0%|          | 0/64 [00:00<?, ?it/s]

100%|██████████| 64/64 [4:02:14<00:00, 227.10s/it]

    positive - 5%
M             50     100    150    200    250    300    350    400
T
50          0.419  0.360  0.325  0.303  0.326  0.287  0.305  0.308
100         0.468  0.400  0.390  0.347  0.350  0.347  0.324  0.334
150         0.525  0.448  0.404  0.405  0.367  0.379  0.360  0.339
200         0.540  0.461  0.428  0.429  0.420  0.374  0.358  0.364
250         0.586  0.502  0.446  0.430  0.407  0.392  0.382  0.371
300         0.618  0.524  0.440  0.442  0.442  0.421  0.405  0.357
350         0.620  0.538  0.469  0.478  0.448  0.426  0.436  0.424
400         0.614  0.550  0.522  0.479  0.432  0.455  0.405  0.364

# Power check
## MA covariance structure

In [7]:
# MA covariance structure
time_ar, time_ma = 0.2, 0.8
space_ar_1, space_ma_1 = 0, 0.8
space_ar_2, space_ma_2 = 0, 0.3

tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "ma_dependence",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "space_ar_1": space_ar_1,
                "space_ma_1": space_ma_1,
                "space_ar_2": space_ar_2,
                "space_ma_2": space_ma_2,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("ma_dependence")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(
    (pl.col("test_statistic") > 4.99).alias(positive_column_name).cast(pl.Float64)
).group_by(
    ["T", "M", "time_ar", "time_ma", "space_ar_1", "space_ma_1", "space_ar_2", "space_ma_2"]
).mean().to_pandas().pivot(
    index="T", columns=["M"], values=[positive_column_name]
)

100%|██████████| 64/64 [4:45:53<00:00, 268.02s/it]

    positive - 5%
M             50   100  150  200  250  300  350  400
T
50          0.994  1.0  1.0  1.0  1.0  1.0  1.0  1.0
100         1.000  1.0  1.0  1.0  1.0  1.0  1.0  1.0
150         1.000  1.0  1.0  1.0  1.0  1.0  1.0  1.0
200         1.000  1.0  1.0  1.0  1.0  1.0  1.0  1.0
250         1.000  1.0  1.0  1.0  1.0  1.0  1.0  1.0
300         1.000  1.0  1.0  1.0  1.0  1.0  1.0  1.0
350         1.000  1.0  1.0  1.0  1.0  1.0  1.0  1.0
400         1.000  1.0  1.0  1.0  1.0  1.0  1.0  1.0

## AR covariance structure

In [8]:
# AR covariance structure
time_ar, time_ma = 0.2, 0.8
space_ar_1, space_ma_1 = 0.8, 0
space_ar_2, space_ma_2 = -0.3, 0

# real gaussian data
is_complex_gaussian = False

tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "ar_dependence",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "space_ar_1": space_ar_1,
                "space_ma_1": space_ma_1,
                "space_ar_2": space_ar_2,
                "space_ma_2": space_ma_2,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("ar_dependence")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(
    (pl.col("test_statistic") > 4.99).alias(positive_column_name).cast(pl.Float64)
).group_by(
    ["T", "M", "time_ar", "time_ma", "space_ar_1", "space_ma_1", "space_ar_2", "space_ma_2"]
).mean().to_pandas().pivot(
    index="T", columns=["M"], values=[positive_column_name]
)

  0%|          | 0/64 [00:00<?, ?it/s]

100%|██████████| 64/64 [4:24:08<00:00, 247.63s/it]

    positive - 5%
M             50   100  150  200  250  300  350  400
T
50            1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
100           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
150           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
200           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
250           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
300           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
350           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
400           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

## ARMA covariance structure

In [9]:
time_ar, time_ma = 0.2, 0.8
space_ar_1, space_ma_1 = 0.3, 0.8
space_ar_2, space_ma_2 = -0.4, 0.3

tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "arma_dependence",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "space_ar_1": space_ar_1,
                "space_ma_1": space_ma_1,
                "space_ar_2": space_ar_2,
                "space_ma_2": space_ma_2,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("arma_dependence")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(
    (pl.col("test_statistic") > 4.99).alias(positive_column_name).cast(pl.Float64)
).group_by(
    ["T", "M", "time_ar", "time_ma", "space_ar_1", "space_ma_1", "space_ar_2", "space_ma_2"]
).mean().to_pandas().pivot(
    index="T", columns=["M"], values=[positive_column_name]
)

100%|██████████| 64/64 [4:45:39<00:00, 267.81s/it]

    positive - 5%
M             50   100  150  200  250  300  350  400
T
50            1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
100           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
150           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
200           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
250           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
300           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
350           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
400           1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

## Non linear dependence

In [10]:
def run(T: int, M: int, burn: int):
    y = non_linear_sample(T, M, burn)
    gpy_result = GPY(y, fs)
    return {
        "T": T,
        "M": M,
        "burn": burn,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }


tasks = []
for T in [40, 50, 80, 150, 200]:
    for M in [40, 50, 80, 150, 200]:
        task = (run, n_repeats, "non_linear_dependence", {"T": T, "M": M, "burn": burn})
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("non_linear_dependence")
df.with_columns(positive=(pl.col("test_statistic") > 1.4).cast(pl.Float64)).group_by(
    ["T", "M"]
).mean().to_pandas().pivot(index="T", columns=["M"], values=["positive"])

  0%|          | 0/25 [00:00<?, ?it/s]

100%|██████████| 25/25 [1:29:59<00:00, 215.99s/it]

    positive
M        40     50     80     150    200
T
40     0.914  0.904  0.904  0.943  0.915
50     0.903  0.930  0.937  0.925  0.936
80     0.888  0.926  0.934  0.933  0.933
150    0.921  0.920  0.923  0.937  0.941
200    0.913  0.935  0.925  0.938  0.939

## Factor model

In [11]:
def run(T: int, M: int, burn: int, K: int, time_ar: float, time_ma: float):
    y = factor_model_sample(T, M, burn, K, time_ar, time_ma)
    gpy_result = GPY(y, fs)
    return {
        "T": T,
        "M": M,
        "burn": burn,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }


time_ar, time_ma = 0, 0.8
K_range = np.arange(1, 5)
T_M_range = [
    (50, 50),
    (50, 100),
    (100, 100),
    (200, 100),
    (300, 200),
    (200, 300),
    (100, 200),
    (200, 400),
    (400, 200),
    (100, 300),
    (300, 100),
]
tasks = []
for T, M in T_M_range:
    for K in K_range:
        task = (
            run,
            n_repeats,
            "factor_model",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "K": K,
                "time_ar": time_ar,
                "time_ma": time_ma,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("factor_model")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(positive=(pl.col("test_statistic") > 1.4).cast(pl.Float64)).group_by(
    ["T", "M", "K"]
).mean().to_pandas().pivot(index="T", columns=["M"], values=[positive_column_name])

  0%|          | 0/44 [00:00<?, ?it/s]

 82%|████████▏ | 36/44 [2:15:09<34:20, 257.50s/it]

## Common random dependence

In [ ]:
def run(N: int, M: int, burn: int):
    y = white_arma_sample(
        N, M, burn, ar=0, ma=0, is_complex_gaussian=is_complex_gaussian
    )
    A = np.random.normal(0, 1, (M, M))
    y = y @ A
    gpy_result = GPY(y, fs, is_complex_gaussian=is_complex_gaussian)
    return {
        "T": T,
        "M": M,
        "burn": burn,
        "space_ar": space_ar,
        "space_ma": space_ma,
        "is_complex_gaussian": is_complex_gaussian,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }


tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "common_random_dependence",
            {"T": T, "M": M, "burn": burn},
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("common_random_dependence")
df.with_columns(positive=(pl.col("p_value") > 1 - level).cast(pl.Float64)).group_by(
    ["T", "M"]
).mean().to_pandas().pivot(index="T", columns=["M"], values=["positive"])

## Rank one dependence

In [ ]:
def run(N: int, M: int, burn: int):
    u = 
    v = 
    y_1 = rank_one_sample(N, M, burn, ar=0, ma=0)
    y = white_arma_sample(N, M, burn, ar=0, ma=0, is_complex_gaussian=is_complex_gaussian)
    A = np.random.normal(0, 1, (M, M))
    y = y @ A
    gpy_result = GPY(y, fs, is_complex_gaussian=is_complex_gaussian)
    return {'N': N, 'M': M, 'burn': burn, 'space_ar': space_ar, 'space_ma': space_ma, 'is_complex_gaussian': is_complex_gaussian, 'test_statistic': gpy_result.test_statistic, 'p_value': gpy_result.p_value}

    gpy_result = GPY(y, fs)
    return {'N': N, 'M': M, 'burn': burn, 'test_statistic': gpy_result.test_statistic, 'p_value': gpy_result.p_value}

tasks = []
for N in N_range:
    for M in M_range: 
        task = (run, n_repeats, 'rank_one_dependence', {'N': N, 'M': M, 'burn': burn})
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch('rank_one_dependence')
df.with_columns(positive=(pl.col('p_value') > 1-level).cast(pl.Float64)).group_by(['N', 'M']).mean().to_pandas().pivot(index='N', columns=['M'], values=['positive'])

# ARCH

In [ ]:
def run(N: int, M: int, burn: int):
    y = arch_sample(
        N,
        M,
        burn,
    )
    gpy_result = GPY(y, fs, is_complex_gaussian=is_complex_gaussian)
    return {
        "N": N,
        "M": M,
        "burn": burn,
        "space_ar": space_ar,
        "space_ma": space_ma,
        "is_complex_gaussian": is_complex_gaussian,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }

    gpy_result = GPY(y, fs)
    return {
        "N": N,
        "M": M,
        "burn": burn,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }


tasks = []
for N in N_range:
    for M in M_range:
        task = (run, n_repeats, "arch", {"N": N, "M": M, "burn": burn})
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("arch")
df.with_columns(positive=(pl.col("p_value") > 1 - level).cast(pl.Float64)).group_by(
    ["N", "M"]
).mean().to_pandas().pivot(index="N", columns=["M"], values=["positive"])