# Power

In [1]:
from joblib import Parallel, delayed
from tqdm import tqdm

import numpy as np
import polars as pl
from gpy_test import GPY
from scipy.linalg import sqrtm
import pickle
from pathlib import Path
from typing import Callable

from data import (
    white_arma_sample,
    arma_covariance,
    non_linear_sample,
    factor_model_sample,
    arch_sample,
)

In [2]:
# for the GPY test, we will always use the following test functions
fs = [lambda x: x, lambda x: x**2]

# we will always evaluate the test against these values of N and M
T_range = np.arange(50, 400 + 50, 50)
M_range = np.arange(50, 400 + 50, 50)

# always repeat an experiment 1000 times
n_repeats = 100

# always throw the first 100 time series samples
burn = 100

# threshold to detect
level = 0.05

# generate real gaussian dataXC
is_complex_gaussian = False

# path to the stored experiment results for easy reloading
data_filepath_format = "data/{experiment_type}/{experiment_id}.pickle"

In [3]:
# Define the functions to store and load experiment results
def run_batch(
    run: Callable, n_repeats: int, experiment_type: str, run_kwargs: dict
) -> None:
    experiment_id = "_".join(f"{key}={value}" for key, value in run_kwargs.items())
    resolved_data_path = Path(
        data_filepath_format.format(
            experiment_type=experiment_type, experiment_id=experiment_id
        )
    )
    if resolved_data_path.exists():
        return

    resolved_data_path.parent.mkdir(parents=True, exist_ok=True)

    results = [run(**run_kwargs) for _ in range(n_repeats)]
    with open(resolved_data_path, "wb") as handle:
        pickle.dump(results, handle)


def load_batch(experiment_type: str) -> pl.DataFrame:
    # load the samples
    all_results = []

    resolved_data_path = Path(
        data_filepath_format.format(
            experiment_type=experiment_type, experiment_id="none"
        )
    ).parent
    for file in resolved_data_path.iterdir():
        if file.stem == ".DS_Store":
            continue

        with open(file, "rb") as handle:
            results = pickle.load(handle)
        all_results += results

    return pl.DataFrame(all_results)

# Level check
# MA time series

In [24]:
def run(T, M, burn, time_ar, time_ma, space_ar, space_ma, is_complex_gaussian):
    y = white_arma_sample(
        T, M, burn, ar=time_ar, ma=time_ma, is_complex_gaussian=is_complex_gaussian
    )
    space_cov = arma_covariance(M, space_ar, space_ma)
    space_cov_sqrt = sqrtm(space_cov)
    y = y @ space_cov_sqrt
    gpy_result = GPY(y, fs, is_complex_gaussian=is_complex_gaussian)
    return {
        "T": T,
        "M": M,
        "burn": burn,
        "time_ar": time_ar,
        "time_ma": time_ma,
        "space_ar": space_ar,
        "space_ma": space_ma,
        "is_complex_gaussian": is_complex_gaussian,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }


time_ar, time_ma = 0.2, 0
space_ar, space_ma = 0, 0

tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "ma_no_dependence",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "space_ar": space_ar,
                "space_ma": space_ma,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("ma_no_dependence")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(
    (pl.col("test_statistic") > 1.4).alias(positive_column_name).cast(pl.Float64)
).group_by(["T", "M", "time_ar", "time_ma"]).mean().to_pandas().pivot(
    index="T", columns=["M"], values=[positive_column_name]
)

100%|██████████| 64/64 [00:06<00:00,  9.50it/s]

    positive - 5%
M             50    100   150   200   250   300   350   400
T
50           0.44  0.41  0.35  0.37  0.29  0.26  0.28  0.29
100          0.44  0.43  0.40  0.50  0.46  0.40  0.41  0.39
150          0.60  0.54  0.41  0.40  0.48  0.39  0.38  0.35
200          0.58  0.56  0.49  0.43  0.51  0.43  0.40  0.49
250          0.57  0.65  0.54  0.46  0.41  0.51  0.41  0.38
300          0.69  0.55  0.60  0.58  0.45  0.43  0.43  0.34
350          0.61  0.55  0.59  0.52  0.45  0.48  0.42  0.45
400          0.68  0.62  0.48  0.52  0.46  0.48  0.61  0.41

## AR time series

In [15]:
time_ar, time_ma = 0, 0.8
space_ar, space_ma = 0, 0

tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "ar_no_dependence",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "space_ar": space_ar,
                "space_ma": space_ma,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("ar_no_dependence")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(
    (pl.col("test_statistic") > 1.4).alias(positive_column_name).cast(pl.Float64)
).group_by(["T", "M", "time_ar", "time_ma"]).mean().to_pandas().pivot(
    index="T", columns=["M"], values=[positive_column_name]
)

  0%|          | 0/64 [00:00<?, ?it/s]

    positive - 5%
M             50    100   150   200   250   300   350   400
T
50           0.42  0.35  0.35  0.28  0.37  0.35  0.29  0.36
100          0.46  0.41  0.52  0.34  0.33  0.41  0.33  0.34
150          0.54  0.48  0.43  0.38  0.37  0.39  0.44  0.32
200          0.58  0.53  0.45  0.43  0.45  0.47  0.33  0.46
250          0.49  0.53  0.44  0.43  0.55  0.45  0.43  0.32
300          0.55  0.57  0.44  0.41  0.45  0.45  0.42  0.38
350          0.68  0.59  0.49  0.44  0.43  0.47  0.37  0.41
400          0.69  0.56  0.58  0.49  0.51  0.47  0.49  0.41

## ARMA time series

In [16]:
time_ar, time_ma = 0.2, 0.8
space_ar, space_ma = 0, 0

tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "arma_no_dependence",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "space_ar": space_ar,
                "space_ma": space_ma,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("arma_no_dependence")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(
    (pl.col("test_statistic") > 1.4).alias(positive_column_name).cast(pl.Float64)
).group_by(["T", "M", "time_ar", "time_ma"]).mean().to_pandas().pivot(
    index="T", columns=["M"], values=[positive_column_name]
)

    positive - 5%
M             50    100   150   200   250   300   350   400
T
50           0.45  0.32  0.31  0.24  0.41  0.27  0.24  0.33
100          0.42  0.39  0.34  0.38  0.36  0.33  0.35  0.41
150          0.51  0.44  0.52  0.40  0.39  0.40  0.44  0.32
200          0.56  0.37  0.37  0.42  0.34  0.38  0.42  0.38
250          0.47  0.56  0.47  0.44  0.42  0.45  0.40  0.31
300          0.63  0.44  0.41  0.42  0.49  0.41  0.43  0.47
350          0.63  0.60  0.47  0.42  0.54  0.41  0.47  0.41
400          0.62  0.49  0.47  0.51  0.48  0.39  0.40  0.36

# Power check
## MA covariance structure

In [17]:
# MA covariance structure
time_ar, time_ma = 0.2, 0.8
space_ar, space_ma = 0, 0.8

tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "ma_dependence",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "space_ar": space_ar,
                "space_ma": space_ma,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("ma_dependence")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(
    (pl.col("test_statistic") > 1.4).alias(positive_column_name).cast(pl.Float64)
).group_by(
    ["T", "M", "time_ar", "time_ma", "space_ar", "space_ma"]
).mean().to_pandas().pivot(
    index="T", columns=["M"], values=[positive_column_name]
)

  0%|          | 0/64 [00:00<?, ?it/s]

    positive - 5%
M             50    100   150   200   250   300   350   400
T
50           0.45  0.43  0.39  0.42  0.33  0.45  0.48  0.47
100          0.49  0.47  0.51  0.51  0.43  0.52  0.38  0.42
150          0.51  0.44  0.55  0.48  0.50  0.49  0.43  0.44
200          0.48  0.49  0.46  0.55  0.51  0.52  0.38  0.44
250          0.55  0.56  0.51  0.52  0.50  0.45  0.52  0.46
300          0.60  0.47  0.49  0.54  0.50  0.54  0.55  0.44
350          0.54  0.55  0.54  0.48  0.47  0.54  0.54  0.52
400          0.58  0.55  0.65  0.43  0.42  0.47  0.53  0.46

## AR covariance structure

In [18]:
# AR covariance structure
time_ar, time_ma = 0.2, 0.8
space_ar, space_ma = 0.2, 0

# real gaussian data
is_complex_gaussian = False

tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "ar_dependence",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "space_ar": space_ar,
                "space_ma": space_ma,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("ar_dependence")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(
    (pl.col("test_statistic") > 1.4).alias(positive_column_name).cast(pl.Float64)
).group_by(
    ["T", "M", "time_ar", "time_ma", "space_ar", "space_ma"]
).mean().to_pandas().pivot(
    index="T", columns=["M"], values=[positive_column_name]
)

    positive - 5%
M             50    100   150   200   250   300   350   400
T
50           0.47  0.32  0.41  0.36  0.35  0.30  0.41  0.33
100          0.48  0.47  0.43  0.32  0.43  0.34  0.37  0.31
150          0.55  0.50  0.51  0.42  0.46  0.32  0.31  0.40
200          0.59  0.50  0.51  0.37  0.45  0.43  0.44  0.40
250          0.59  0.48  0.51  0.48  0.38  0.34  0.40  0.36
300          0.60  0.54  0.50  0.41  0.45  0.38  0.44  0.44
350          0.58  0.54  0.51  0.41  0.36  0.45  0.44  0.46
400          0.61  0.59  0.48  0.51  0.51  0.47  0.44  0.48

## ARMA covariance structure

In [19]:
time_ar, time_ma = 0.2, 0.8
space_ar, space_ma = 0.2, 0.8

tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "arma_dependence",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "time_ar": time_ar,
                "time_ma": time_ma,
                "space_ar": space_ar,
                "space_ma": space_ma,
                "is_complex_gaussian": is_complex_gaussian,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("arma_dependence")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(
    (pl.col("test_statistic") > 1.4).alias(positive_column_name).cast(pl.Float64)
).group_by(
    ["T", "M", "time_ar", "time_ma", "space_ar", "space_ma"]
).mean().to_pandas().pivot(
    index="T", columns=["M"], values=[positive_column_name]
)

    positive - 5%
M             50    100   150   200   250   300   350   400
T
50           0.51  0.51  0.56  0.46  0.38  0.48  0.52  0.47
100          0.51  0.60  0.42  0.39  0.51  0.46  0.50  0.40
150          0.60  0.54  0.51  0.51  0.49  0.52  0.43  0.49
200          0.57  0.45  0.54  0.62  0.51  0.53  0.49  0.58
250          0.55  0.52  0.56  0.58  0.52  0.50  0.57  0.57
300          0.57  0.64  0.50  0.61  0.55  0.48  0.47  0.47
350          0.58  0.52  0.56  0.51  0.51  0.43  0.49  0.59
400          0.59  0.58  0.50  0.53  0.50  0.48  0.46  0.52

## Non linear dependence

In [20]:
def run(T: int, M: int, burn: int):
    y = non_linear_sample(T, M, burn)
    gpy_result = GPY(y, fs)
    return {
        "T": T,
        "M": M,
        "burn": burn,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }


tasks = []
for T in [40, 50, 80, 150, 200]:
    for M in [40, 50, 80, 150, 200]:
        task = (run, n_repeats, "non_linear_dependence", {"T": T, "M": M, "burn": burn})
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("non_linear_dependence")
df.with_columns(positive=(pl.col("test_statistic") > 1.4).cast(pl.Float64)).group_by(
    ["T", "M"]
).mean().to_pandas().pivot(index="T", columns=["M"], values=["positive"])

    positive
M        40    50    80    150   200
T
40      0.87  0.92  0.91  0.94  0.93
50      0.89  0.89  0.93  0.95  0.94
80      0.94  0.92  0.92  0.93  0.92
150     0.88  0.93  0.94  0.89  0.94
200     0.97  0.96  0.98  0.91  0.92

## Factor model

In [12]:
def run(T: int, M: int, burn: int, K: int, time_ar: float, time_ma: float):
    y = factor_model_sample(T, M, burn, K, time_ar, time_ma)
    gpy_result = GPY(y, fs)
    return {
        "T": T,
        "M": M,
        "burn": burn,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }


time_ar, time_ma = 0, 0.8
K_range = np.arange(1, 5)
T_M_range = [
    (50, 50),
    (50, 100),
    (100, 100),
    (200, 100),
    (300, 200),
    (200, 300),
    (100, 200),
    (200, 400),
    (400, 200),
    (100, 300),
    (300, 100),
]
tasks = []
for T, M in T_M_range:
    for K in K_range:
        task = (
            run,
            n_repeats,
            "factor_model",
            {
                "T": T,
                "M": M,
                "burn": burn,
                "K": K,
                "time_ar": time_ar,
                "time_ma": time_ma,
            },
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("factor_model")
positive_column_name = f"positive - {level:.0%}"
df.with_columns(positive=(pl.col("test_statistic") > 1.4).cast(pl.Float64)).group_by(
    ["T", "M", "K"]
).mean().to_pandas().pivot(index="T", columns=["M"], values=[positive_column_name])

  0%|          | 0/44 [00:00<?, ?it/s]

100%|██████████| 44/44 [00:07<00:00,  6.24it/s]

ValueError: Convergence issue: the limit covariance matrix is not definite non-negative: matrix=array([[6.55869079e+02+0.j, 9.77313149e+04+0.j],
       [9.77313149e+04+0.j, 1.20488499e+07+0.j]]), eigs=array([-1.36845700e+02,  1.20496427e+07])

## Common random dependence

In [ ]:
def run(N: int, M: int, burn: int):
    y = white_arma_sample(
        N, M, burn, ar=0, ma=0, is_complex_gaussian=is_complex_gaussian
    )
    A = np.random.normal(0, 1, (M, M))
    y = y @ A
    gpy_result = GPY(y, fs, is_complex_gaussian=is_complex_gaussian)
    return {
        "T": T,
        "M": M,
        "burn": burn,
        "space_ar": space_ar,
        "space_ma": space_ma,
        "is_complex_gaussian": is_complex_gaussian,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }


tasks = []
for T in T_range:
    for M in M_range:
        task = (
            run,
            n_repeats,
            "common_random_dependence",
            {"T": T, "M": M, "burn": burn},
        )
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("common_random_dependence")
df.with_columns(positive=(pl.col("p_value") > 1 - level).cast(pl.Float64)).group_by(
    ["T", "M"]
).mean().to_pandas().pivot(index="T", columns=["M"], values=["positive"])

## Rank one dependence

In [ ]:
def run(N: int, M: int, burn: int):
    u = 
    v = 
    y_1 = rank_one_sample(N, M, burn, ar=0, ma=0)
    y = white_arma_sample(N, M, burn, ar=0, ma=0, is_complex_gaussian=is_complex_gaussian)
    A = np.random.normal(0, 1, (M, M))
    y = y @ A
    gpy_result = GPY(y, fs, is_complex_gaussian=is_complex_gaussian)
    return {'N': N, 'M': M, 'burn': burn, 'space_ar': space_ar, 'space_ma': space_ma, 'is_complex_gaussian': is_complex_gaussian, 'test_statistic': gpy_result.test_statistic, 'p_value': gpy_result.p_value}

    gpy_result = GPY(y, fs)
    return {'N': N, 'M': M, 'burn': burn, 'test_statistic': gpy_result.test_statistic, 'p_value': gpy_result.p_value}

tasks = []
for N in N_range:
    for M in M_range: 
        task = (run, n_repeats, 'rank_one_dependence', {'N': N, 'M': M, 'burn': burn})
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch('rank_one_dependence')
df.with_columns(positive=(pl.col('p_value') > 1-level).cast(pl.Float64)).group_by(['N', 'M']).mean().to_pandas().pivot(index='N', columns=['M'], values=['positive'])

# ARCH

In [ ]:
def run(N: int, M: int, burn: int):
    y = arch_sample(
        N,
        M,
        burn,
    )
    gpy_result = GPY(y, fs, is_complex_gaussian=is_complex_gaussian)
    return {
        "N": N,
        "M": M,
        "burn": burn,
        "space_ar": space_ar,
        "space_ma": space_ma,
        "is_complex_gaussian": is_complex_gaussian,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }

    gpy_result = GPY(y, fs)
    return {
        "N": N,
        "M": M,
        "burn": burn,
        "test_statistic": gpy_result.test_statistic,
        "p_value": gpy_result.p_value,
    }


tasks = []
for N in N_range:
    for M in M_range:
        task = (run, n_repeats, "arch", {"N": N, "M": M, "burn": burn})
        tasks.append(task)

results = Parallel(n_jobs=-1)(delayed(run_batch)(*task) for task in tqdm(tasks))

df = load_batch("arch")
df.with_columns(positive=(pl.col("p_value") > 1 - level).cast(pl.Float64)).group_by(
    ["N", "M"]
).mean().to_pandas().pivot(index="N", columns=["M"], values=["positive"])